version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [ "react" ]
  environment = [ "nodejs", "browser", "jest", "mocha", "cypress", "jquery" ]
  dialect = "typescript"
  dependency_file_paths = [ "WebSite/" ]

[[transformers]]
name = "dotnet-format"
enabled = false

[[transformers]]
name = "prettier"
enabled = false
