version = 1
test_patterns = [
  "*/cypress/**",
  "**/__test__/**",
  "*.spec.*",
  "WebSite.Tests/**"
]
exclude_patterns = [
  "**/node_modules/",
  "**/dist/",
  "**/distro/",
  "*/coverage/",
  "*/bin/",
  "*/obj/",
  "*/nls/",
  "*/BuildFiles/",
  "*/Ext-ux-4/",
  "*/ExtJs-4-1/",
  "*/SharedScripts/Libs/",
  "*/Scripts/",
  "*/webpack.config.js"
]

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [ "react" ]
  environment = [ "nodejs", "browser", "jest", "mocha", "cypress", "jquery" ]
  dialect = "typescript"
  dependency_file_paths = [ "WebSite/" ]

[[transformers]]
name = "dotnet-format"
enabled = false

[[transformers]]
name = "prettier"
enabled = false
